//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Veritabani_Homework.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AdminLogin
    {
        public int AdminNo { get; set; }
        [Required(ErrorMessage = "Bu alan boþ geçilemez !")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Bu alan boþ geçilemez !")]
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    }
}
